sudo: false
language: python
matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py33
      python: 3.3
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=flake8
      python: 2.7
install:
  - pip install coveralls tox 
script:
  - tox -e $TOXENV
after_success: coveralls
